// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string
  created_at: number
}

export type Entity<T> = {
  [K in keyof T]: T[K]
} & BaseEntity

export type Meta = {
  page: number
  total: number
  total_pages: number
}

export type User = Entity<{
  first_name: string
  last_name: string
  email: string
  role: 'ADMIN' | 'USER'
  team_id: string
  bio: string
}>

export type AuthResponse = {
  jwt: string
  user: User
}

export type Team = Entity<{
  name: string
  description: string
}>

export type Discussion = Entity<{
  title: string
  body: string
  team_id: string
  author: User
}>

export type Comment = Entity<{
  body: string
  discussion_id: string
  author: User
}>
